// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Blog documents */
interface BlogDocumentData {
  /**
   * thumbnail field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  thumbnail: prismic.ImageField<never>;
  /**
   * title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Blog → Slice Zone*
 *
 */
type BlogDocumentDataSlicesSlice =
  | QuoteSlice
  | ListTextSlice
  | DescriptionSlice
  | NormalTextSlice
  | TitleSlice
  | ImageSlice;
/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;
export type AllDocumentTypes = BlogDocument;
/**
 * Primary content in Description → Primary
 *
 */
interface DescriptionSliceDefaultPrimary {
  /**
   * Text field in *Description → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text: prismic.KeyTextField;
}
/**
 * Default variation for Description Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DescriptionSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Description*
 *
 */
type DescriptionSliceVariation = DescriptionSliceDefault;
/**
 * Description Shared Slice
 *
 * - **API ID**: `description`
 * - **Description**: `Description`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DescriptionSlice = prismic.SharedSlice<
  "description",
  DescriptionSliceVariation
>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Image*
 *
 */
type ImageSliceVariation = ImageSliceDefault;
/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;
/**
 * Item in ListText → Items
 *
 */
export interface ListTextSliceDefaultItem {
  /**
   * Item field in *ListText → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list_text.items[].item
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  item: prismic.RichTextField;
}
/**
 * Default variation for ListText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ListTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ListTextSliceDefaultItem>
>;
/**
 * Slice variation for *ListText*
 *
 */
type ListTextSliceVariation = ListTextSliceDefault;
/**
 * ListText Shared Slice
 *
 * - **API ID**: `list_text`
 * - **Description**: `ListText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ListTextSlice = prismic.SharedSlice<
  "list_text",
  ListTextSliceVariation
>;
/**
 * Primary content in NormalText → Primary
 *
 */
interface NormalTextSliceDefaultPrimary {
  /**
   * normalText field in *NormalText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: normal_text.primary.normal_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  normal_text: prismic.KeyTextField;
}
/**
 * Default variation for NormalText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NormalTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NormalTextSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *NormalText*
 *
 */
type NormalTextSliceVariation = NormalTextSliceDefault;
/**
 * NormalText Shared Slice
 *
 * - **API ID**: `normal_text`
 * - **Description**: `NormalText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NormalTextSlice = prismic.SharedSlice<
  "normal_text",
  NormalTextSliceVariation
>;
/**
 * Primary content in Quote → Primary
 *
 */
interface QuoteSliceDefaultPrimary {
  /**
   * content field in *Quote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  content: prismic.KeyTextField;
  /**
   * avatar field in *Quote → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.avatar
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  avatar: prismic.ImageField<never>;
  /**
   * name field in *Quote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField;
  /**
   * position field in *Quote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.position
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  position: prismic.KeyTextField;
}
/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Quote*
 *
 */
type QuoteSliceVariation = QuoteSliceDefault;
/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: `Quote`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;
/**
 * Primary content in Title → Primary
 *
 */
interface TitleSliceDefaultPrimary {
  /**
   * Topic field in *Title → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title.primary.topic
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  topic: prismic.KeyTextField;
  /**
   * Label field in *Title → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title.primary.label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismic.KeyTextField;
}
/**
 * Default variation for Title Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Title*
 *
 */
type TitleSliceVariation = TitleSliceDefault;
/**
 * Title Shared Slice
 *
 * - **API ID**: `title`
 * - **Description**: `Title`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleSlice = prismic.SharedSlice<"title", TitleSliceVariation>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogDocument,
      AllDocumentTypes,
      DescriptionSliceDefaultPrimary,
      DescriptionSliceDefault,
      DescriptionSliceVariation,
      DescriptionSlice,
      ImageSliceDefaultPrimary,
      ImageSliceDefault,
      ImageSliceVariation,
      ImageSlice,
      ListTextSliceDefaultItem,
      ListTextSliceDefault,
      ListTextSliceVariation,
      ListTextSlice,
      NormalTextSliceDefaultPrimary,
      NormalTextSliceDefault,
      NormalTextSliceVariation,
      NormalTextSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceDefault,
      QuoteSliceVariation,
      QuoteSlice,
      TitleSliceDefaultPrimary,
      TitleSliceDefault,
      TitleSliceVariation,
      TitleSlice,
    };
  }
}
