// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  description: defineAsyncComponent(() => import("./Description/index.vue")),
  image: defineAsyncComponent(() => import("./Image/index.vue")),
  list_text: defineAsyncComponent(() => import("./ListText/index.vue")),
  normal_text: defineAsyncComponent(() => import("./NormalText/index.vue")),
  quote: defineAsyncComponent(() => import("./Quote/index.vue")),
  title: defineAsyncComponent(() => import("./Title/index.vue")),
});
